defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

<<<<<<< HEAD
title: Se√±or Pinky
subtitle: Community Advocate
description: "üëÅÔ∏èüíó2Ô∏è‚É£üí™üèΩ‚ôÄÔ∏è‚öôÔ∏èüë©üèΩ‚Äçüíª"
avatar: "/assets/images/CovidSenorPinky.jpg"
=======
paginate: 10
paginate_path: "/blog/page:num/"

title: Christian Ezeani
subtitle: Full-Stack Developer
>>>>>>> 57fbcdbbdec72d75999554a1040e1813291c5b4c

left_side:
  background_image: "./assets/images/left-background.jpg"
  background_color: "#DDA0DD"
  close_button_color: "#F00"
  text_color: "#FF1493"

footer:
  copyright_text: "&copy; Se√±or Pinky&trade;"

# Side Menu Links
menu:
  - text: Intro
    link: /
    icon: ""

  - text: About Me
    link: /about-me
    icon: ""

  - text: Blog Posts
    link: /posts
    icon: ""
    
#  - text: Skills & Offers
#    link: /skills-and-offers
#    icon: ""

#  - text: My Resume
#    link: /resume
#    icon: ""

<<<<<<< HEAD
  - text: Contact Me
    link: /contact
=======
  - text: Blog Posts
    link: /blog
>>>>>>> 57fbcdbbdec72d75999554a1040e1813291c5b4c
    icon: ""


# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/mikerostx
    icon: fab fa-linkedin

  - name: twitter
    link: https://www.twitter.com/MikeRosTX
    icon: fab fa-twitter

  - name: github
    link: https://github.com/MikeRosTX
    icon: fab fa-github

  - name: instagram
    link: https://www.instagram.com/MikeRosTX
    icon: fab fa-instagram


    
