defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: SeÃ±or Pinky
subtitle: Community Advocate
description: "ğŸ‘ï¸ğŸ’—2ï¸âƒ£ğŸ’ªğŸ½â™€ï¸âš™ï¸ğŸ‘©ğŸ½â€ğŸ’»"
avatar: "/assets/images/CovidSenorPinky.jpg"
paginate: 10
paginate_path: "/blog/page:num/"


left_side:
  background_image: "./assets/images/left-background.jpg"
  background_color: "#DDA0DD"
  close_button_color: "#F00"
  text_color: "#FF1493"

footer:
  copyright_text: "&copy; SeÃ±or Pinky&trade;"

# Side Menu Links
menu:
  - text: Intro
    link: /
    icon: ""

  - text: About Me
    link: /about-me
    icon: ""

  - text: Blog Posts
    link: /posts
    icon: ""
    
#  - text: Skills & Offers
#    link: /skills-and-offers
#    icon: ""

#  - text: My Resume
#    link: /resume
#    icon: ""

  - text: Contact Me
    link: /contact
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/mikerostx
    icon: fab fa-linkedin

  - name: twitter
    link: https://www.twitter.com/MikeRosTX
    icon: fab fa-twitter

  - name: github
    link: https://github.com/MikeRosTX
    icon: fab fa-github

  - name: instagram
    link: https://www.instagram.com/MikeRosTX
    icon: fab fa-instagram


    
